services:
  backend:
    container_name: omnihr
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8001:8001
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      POSTGRES_DB: omnihr_db
      POSTGRES_HOST: localhost
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5435
      JWT_SECRET_KEY: RnNiTjM3d1FrcXZWSm1FcUNXeWVOSUZtWUpFS0hEcnM9SEURE
      API_SECRET_KEY: a3hBckpHT3h3d0tQRFNLVHZGQlRVR0hQMjR5WmJvQkQ9QkhHTQ==
      REDIS_HOST: redis

  db:
    image: postgres:14.1-alpine
    restart: always
    container_name: omnihr_db
    volumes:
      - .dbdata:/var/lib/postgres
    ports:
      - "5435:5435"
    environment:
      - POSTGRES_DB=omnihr_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    command: -p 5435

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    container_name: omnihr_redis