companies:
  - id: 1
    columns:
      - "id"
      - "first_name"
      - "last_name"
      - "contact_info"
      - "department"
      - "position"
      - "location"
      - "status"
      - "created_at"
      - "updated_at"
  - id: 2
    columns:
      - "id"
      - "first_name"
      - "last_name"
      - "created_at"
      - "updated_at"